dofile("tests/config_test.lua")
dofile("tests/economy_test.lua")
dofile("tests/stakes_test.lua")
dofile("tests/condition_test.lua")
dofile("tests/storage_test.lua")
dofile("tests/persistence_test.lua")
dofile("tests/catalog_test.lua")
dofile("tests/label_test.lua")
dofile("tests/binder_test.lua")
dofile("tests/binder_ui_test.lua")
dofile("tests/buyout_test.lua")
dofile("tests/settlement_test.lua")
dofile("tests/buyout_ui_test.lua")
dofile("tests/run_end_test.lua")

print("all Gradelatro foundation tests ok")
