return {
    descriptions = {
        Mod = {
            Gradelatro = {
                name = "Gradelatro",
                text = {
                    "围绕小丑牌收藏、认证、评级",
                    "与轻量市场体系的扩展模组。"
                }
            }
        }
    },
    misc = {
        dictionary = {
            grdl_b_buyout = "买断藏卡",
            grdl_b_binder = "Gradelatro 卡册",
            grdl_b_confirm_buyout = "买断",
            grdl_b_skip_buyout = "跳过",
            grdl_b_select = "选择",
            grdl_b_selected = "已选",
            grdl_b_grade = "送评",
            grdl_b_desk = "送评服务台",
            grdl_b_market = "市场",
            grdl_b_sell = "出售",
            grdl_b_confirm_sell = "确认",
            grdl_b_carry = "带入赛局",
            grdl_b_withdraw_carry = "收回随行",
            grdl_k_status_carried = "随行中",
            grdl_k_reason_carry_taken = "已有随行卡牌。",
            grdl_k_reason_no_carry = "当前没有随行卡牌。",
            grdl_k_reason_missing_condition = "卡牌品相数据缺失。",
            grdl_k_market_title = "Gradelatro 市场",
            grdl_k_market_empty = "没有可出售的卡牌。",
            grdl_k_tab_submit = "选择送评",
            grdl_k_tab_progress = "评级进度",
            grdl_k_tab_sell = "出售",
            grdl_k_tab_trends = "行情",
            grdl_k_queue_empty = "评级队列为空。",
            grdl_k_heat_hot = "火热",
            grdl_k_heat_rising = "上行",
            grdl_k_heat_stable = "平稳",
            grdl_k_heat_cooling = "遇冷",
            grdl_k_reason_not_sellable = "此卡当前不可出售。",
            grdl_k_desk_title = "送评服务台",
            grdl_k_desk_empty = "没有可送评的原卡。",
            grdl_k_badge_ungraded = "未评级",
            grdl_k_stat_owned = "持有",
            grdl_k_stat_raw = "原卡",
            grdl_k_stat_graded = "已评级",
            grdl_k_stat_queue = "队列",
            grdl_k_detail_source = "来源模组",
            grdl_k_detail_rarity = "稀有度",
            grdl_k_detail_edition = "版本",
            grdl_k_detail_date = "获得日期",
            grdl_k_detail_price = "入手价",
            grdl_k_detail_psa = "PSA评级",
            grdl_k_rarity_common = "普通",
            grdl_k_rarity_uncommon = "罕见",
            grdl_k_rarity_rare = "稀有",
            grdl_k_rarity_legendary = "传说",
            grdl_k_rarity_exotic = "异域",
            grdl_k_rarity_unknown_high = "未知",
            grdl_k_grading_ready = "已完成",
            grdl_k_service_economy = "经济",
            grdl_k_service_standard = "标准",
            grdl_k_service_priority = "优先",
            grdl_k_service_express = "特快",
            grdl_k_binder_title = "Gradelatro 卡册",
            grdl_k_binder_empty = "尚未收藏 Gradelatro 卡牌。",
            grdl_k_edition_base = "基础",
            grdl_k_edition_foil = "闪箔",
            grdl_k_edition_holographic = "镭射",
            grdl_k_edition_polychrome = "多彩",
            grdl_k_edition_negative = "负片",
            grdl_k_buyout_title = "Gradelatro 买断",
            grdl_k_buyout_subtitle = "选择本赛局结束时持有的小丑牌并收入卡册。",
            grdl_k_buyout_empty = "没有可买断的小丑牌。",
            grdl_k_buyout_blocked = "暂不可买断",
            grdl_k_reason_rarity_locked = "当前底注门槛不足。",
            grdl_k_reason_not_in_catalog = "不在当前小丑牌卡池中。",
            grdl_k_reason_selection_limit = "已达到选择上限。",
            grdl_k_reason_insufficient_funds = "Ⓖ不足。",
            grdl_k_reason_not_in_offer = "此牌不在本次买断清单中。",
            grdl_k_reason_no_selection = "至少选择一张牌。",
            grdl_k_reason_missing_namespace = "Gradelatro 状态不可用。",
            grdl_k_reason_missing_state = "买断状态不可用。",
            grdl_k_reason_missing_collection = "卡册数据不可用。",
            grdl_k_reason_missing_config = "Gradelatro 配置不可用。",
            grdl_k_reason_card_not_found = "未找到该卡牌。",
            grdl_k_reason_not_raw = "仅未评级原卡可送评。",
            grdl_k_reason_unknown_service = "未知评级服务。",
            grdl_k_reason_unknown = "暂不可用。",
            grdl_k_status_raw = "原卡",
            grdl_k_status_graded = "已评级",
            grdl_k_status_queued = "评级中",
            grdl_k_status_sold = "已出售",
            grdl_k_status_lost = "已损失",
            grdl_k_status_unknown = "未知"
        },
        v_dictionary = {
            grdl_k_stat_g = "Ⓖ#1#",
            grdl_k_selected_count = "已选 #1#/#2#",
            grdl_k_buyout_total = "合计：Ⓖ#1#",
            grdl_k_buyout_price = "Ⓖ#1#",
            grdl_k_buyout_summary = "已选 #1#/#2#  |  合计：Ⓖ#3#  |  持有：Ⓖ#4#",
            grdl_k_grading_fee = "Ⓖ#1#",
            grdl_k_grading_revealed = "揭晓了 #1# 张卡牌的评级结果！",
            grdl_k_market_sold = "已售出：+Ⓖ#1#",
            grdl_k_binder_hidden = "#1# 张卡牌因模组未加载而隐藏"
        }
    }
}
